# Generated by Django 5.1.5 on 2025-02-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_two_factor_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_two_factor_active',
            field=models.BooleanField(default=True),
        ),
    ]
