# Generated by Django 5.1.5 on 2025-02-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_two_factor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_two_factor_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_two_factor_mail',
            field=models.BooleanField(default=False),
        ),
    ]
