# Generated by Django 5.1.5 on 2025-02-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_is_two_factor_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_two_factor_active',
        ),
    ]
