# Generated by Django 5.1.5 on 2025-04-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_is_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(default='/media/avatars/default_avatar.png'),
        ),
    ]
