# Generated by Django 5.1.5 on 2025-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_two_factor_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mail_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
