# Generated by Django 5.1.5 on 2025-02-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_mail_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_type',
            field=models.CharField(choices=[('qr', 'qr'), ('mail', 'mail')], default='mail'),
        ),
    ]
