# Generated by Django 5.1.5 on 2025-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_is_mail_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_two_factor_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
