# Generated by Django 5.1.5 on 2025-02-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_two_factor_type'),
        ('users', '0006_alter_userprofile_is_active'),
    ]

    operations = [
    ]
