# Generated by Django 5.1.5 on 2025-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_tournament_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
