# Generated by Django 5.1.5 on 2025-04-02 08:14

import dashboards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(default=dashboards.models.Participant.get_unknown_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='games_as_player1', to='dashboards.participant'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(default=dashboards.models.Participant.get_unknown_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='games_as_player2', to='dashboards.participant'),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='dashboards.tournament'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(default=dashboards.models.Participant.get_unknown_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='games_won', to='dashboards.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
