# Generated by Django 5.1.5 on 2025-04-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_alter_game_player1_alter_game_player2_and_more'),
        ('dashboards', '0006_alter_participant_name'),
    ]

    operations = [
    ]
