# Generated by Django 5.1.5 on 2025-01-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendance', '0005_userprofile_is_logged_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=255),
        ),
    ]
