# Generated by Django 5.1.5 on 2025-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendance', '0003_userprofile_theme_alter_friendship_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTimeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_users', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('total_tournaments', models.IntegerField(default=0)),
                ('total_points_scored', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='playerstatistics',
            name='total_score',
        ),
    ]
