# Generated by Django 5.1.5 on 2025-01-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendance', '0007_rename_is_logged_in_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-16 10:30:00+00:00'),
            preserve_default=False,
        ),
    ]
